const fs = require('fs');
const path = require('path');

// tingkat kesulitan = panjang kata
const LEVELS = {
  mudah: 'Mudah (4-5 huruf)',
  sedang: 'Sedang (6-7 huruf)',
  sulit: 'Sulit (8+ huruf)',
};
const DEFAULT_LEVEL = 'mudah';

// [KATA, petunjuk]
const BANK = {
  mudah: [
    // ===== BENDA =====
    ['BUKU', 'Benda'],
    ['MEJA', 'Perabot'],
    ['KURSI', 'Perabot'],
    ['BOLA', 'Olahraga'],
    ['PENA', 'Alat tulis'],
    ['PISAU', 'Alat'],
    ['GELAS', 'Benda'],
    ['KACA', 'Benda'],
    ['JAM', 'Benda'],
    ['TAS', 'Benda'],
    ['KAIN', 'Benda'],
    ['KOIN', 'Benda'],
    ['KADO', 'Benda'],
    ['KUNCI', 'Benda'],
    ['SAPU', 'Benda'],
    ['SABUN', 'Benda'],
    ['SIKAT', 'Benda'],
    ['KABEL', 'Elektronik'],
    ['LAMPU', 'Elektronik'],
    ['RADIO', 'Elektronik'],
    ['MOUSE', 'Elektronik'],
    ['KIPAS', 'Elektronik'],

    // ===== HEWAN =====
    ['SAPI', 'Hewan'],
    ['IKAN', 'Hewan'],
    ['BEBEK', 'Hewan'],
    ['AYAM', 'Hewan'],
    ['KUCING', 'Hewan'],
    ['TIKUS', 'Hewan'],
    ['KAMBING', 'Hewan'],
    ['KUDA', 'Hewan'],
    ['BURUNG', 'Hewan'],
    ['SEMUT', 'Hewan'],
    ['LEBAH', 'Hewan'],
    ['ULAT', 'Hewan'],
    ['CACING', 'Hewan'],
    ['KODOK', 'Hewan'],
    ['IKAN', 'Hewan'],

    // ===== MAKANAN =====
    ['NASI', 'Makanan'],
    ['SATE', 'Makanan'],
    ['SOTO', 'Makanan'],
    ['BAKSO', 'Makanan'],
    ['ROTI', 'Makanan'],
    ['MIE', 'Makanan'],
    ['TELUR', 'Makanan'],
    ['TAHU', 'Makanan'],
    ['TEMPE', 'Makanan'],
    ['BUBUR', 'Makanan'],
    ['SUP', 'Makanan'],
    ['CAKE', 'Makanan'],
    ['DONAT', 'Makanan'],
    ['PIZZA', 'Makanan'],
    ['BURGER', 'Makanan'],
    ['KEJU', 'Makanan'],
    ['DAGING', 'Makanan'],
    ['IKAN', 'Makanan'],
    ['SAMBAL', 'Makanan'],
    ['KERUPUK', 'Makanan'],

    // ===== BUAH =====
    ['APEL', 'Buah'],
    ['JERUK', 'Buah'],
    ['MELON', 'Buah'],
    ['MANGGA', 'Buah'],
    ['PEPAYA', 'Buah'],
    ['PISANG', 'Buah'],
    ['ANGGUR', 'Buah'],
    ['JAMBU', 'Buah'],
    ['SALAK', 'Buah'],
    ['NANAS', 'Buah'],
    ['LEMON', 'Buah'],
    ['DURIAN', 'Buah'],
    ['KIWI', 'Buah'],

    // ===== TEMPAT =====
    ['RUMAH', 'Tempat'],
    ['TOKO', 'Tempat'],
    ['PASAR', 'Tempat'],
    ['KAFE', 'Tempat'],
    ['KANTOR', 'Tempat'],
    ['TAMAN', 'Tempat'],
    ['PANTAI', 'Tempat'],
    ['KOLAM', 'Tempat'],
    ['KELAS', 'Tempat'],
    ['HOTEL', 'Tempat'],

    // ===== ALAM =====
    ['LAUT', 'Alam'],
    ['HUJAN', 'Alam'],
    ['AWAN', 'Alam'],
    ['ANGIN', 'Alam'],
    ['HUTAN', 'Alam'],
    ['BUKIT', 'Alam'],
    ['GUNUNG', 'Alam'],
    ['SUNGAI', 'Alam'],
    ['BATU', 'Alam'],
    ['PASIR', 'Alam'],

    // ===== PAKAIAN =====
    ['BAJU', 'Pakaian'],
    ['TOPI', 'Pakaian'],
    ['CELANA', 'Pakaian'],
    ['KAOS', 'Pakaian'],
    ['ROK', 'Pakaian'],
    ['JAKET', 'Pakaian'],
    ['SEPATU', 'Pakaian'],
    ['KEMEJA', 'Pakaian'],
    ['SARUNG', 'Pakaian'],
    ['DASI', 'Pakaian'],

    // ===== KENDARAAN =====
    ['MOBIL', 'Kendaraan'],
    ['MOTOR', 'Kendaraan'],
    ['BECAK', 'Kendaraan'],
    ['KAPAL', 'Kendaraan'],
    ['BUS', 'Kendaraan'],
    ['TRUK', 'Kendaraan'],
    ['TAXI', 'Kendaraan'],
    ['SEPEDA', 'Kendaraan'],
    ['ROKET', 'Kendaraan'],

    // ===== MINUMAN =====
    ['KOPI', 'Minuman'],
    ['SUSU', 'Minuman'],
    ['TEH', 'Minuman'],
    ['JUS', 'Minuman'],
    ['SODA', 'Minuman'],
    ['AIR', 'Minuman'],
    ['SIRUP', 'Minuman'],

    // ===== PROFESI =====
    ['GURU', 'Profesi'],
    ['DOKTER', 'Profesi'],
    ['POLISI', 'Profesi'],
    ['PILOT', 'Profesi'],
    ['HAKIM', 'Profesi'],
    ['PETANI', 'Profesi'],
    ['KOKI', 'Profesi'],
    ['BIDAN', 'Profesi'],

    // ===== LAINNYA =====
    ['PAGI', 'Waktu'],
    ['SIANG', 'Waktu'],
    ['MALAM', 'Waktu'],
    ['SENJA', 'Waktu'],
    ['MINGGU', 'Waktu'],
    ['JANUARI', 'Bulan'],
    ['MARET', 'Bulan'],
    ['APRIL', 'Bulan'],
    ['MEI', 'Bulan'],
    ['JUNI', 'Bulan'],
    ['MERAH', 'Warna'],
    ['BIRU', 'Warna'],
    ['HIJAU', 'Warna'],
    ['PUTIH', 'Warna'],
    ['HITAM', 'Warna'],
  ],

  sedang: [
    // ===== HEWAN =====
    ['KUCING', 'Hewan'],
    ['HARIMAU', 'Hewan'],
    ['KELINCI', 'Hewan'],
    ['GAJAH', 'Hewan'],
    ['JERAPAH', 'Hewan'],
    ['ZEBRA', 'Hewan'],
    ['MONYET', 'Hewan'],
    ['GORILA', 'Hewan'],
    ['PANDA', 'Hewan'],
    ['KOALA', 'Hewan'],
    ['KANGURU', 'Hewan'],
    ['BUAYA', 'Hewan'],
    ['KURA-KURA', 'Hewan'],
    ['LUMBA-LUMBA', 'Hewan'],
    ['HIU', 'Hewan'],
    ['PAUS', 'Hewan'],
    ['PENGUIN', 'Hewan'],
    ['MERPATI', 'Hewan'],
    ['KUPU-KUPU', 'Hewan'],
    ['BELALANG', 'Hewan'],

    // ===== BUAH =====
    ['MANGGA', 'Buah'],
    ['PISANG', 'Buah'],
    ['ANGGUR', 'Buah'],
    ['DURIAN', 'Buah'],
    ['SEMANGKA', 'Buah'],
    ['RAMBUTAN', 'Buah'],
    ['MELON', 'Buah'],
    ['PEPAYA', 'Buah'],
    ['NANGKA', 'Buah'],
    ['MANGGIS', 'Buah'],
    ['MARKISA', 'Buah'],
    ['STROBERI', 'Buah'],
    ['ALPUKAT', 'Buah'],
    ['SIRSAK', 'Buah'],
    ['BELIMBING', 'Buah'],
    ['DELIMA', 'Buah'],

    // ===== MAKANAN =====
    ['RENDANG', 'Makanan'],
    ['NASI GORENG', 'Makanan'],
    ['MARTABAK', 'Makanan'],
    ['PEMPEK', 'Makanan'],
    ['BATAGOR', 'Makanan'],
    ['SIOMAY', 'Makanan'],
    ['GADO-GADO', 'Makanan'],
    ['KETOPRAK', 'Makanan'],
    ['SOMAY', 'Makanan'],
    ['LONTONG', 'Makanan'],
    ['OPOR', 'Makanan'],
    ['RAWON', 'Makanan'],
    ['GUDEG', 'Makanan'],
    ['PECEL', 'Makanan'],
    ['SATE AYAM', 'Makanan'],
    ['MIE AYAM', 'Makanan'],
    ['NASI PADANG', 'Makanan'],
    ['AYAM GORENG', 'Makanan'],
    ['AYAM BAKAR', 'Makanan'],

    // ===== BENDA =====
    ['PAYUNG', 'Benda'],
    ['DOMPET', 'Benda'],
    ['KAMERA', 'Elektronik'],
    ['LAPTOP', 'Elektronik'],
    ['KULKAS', 'Elektronik'],
    ['TELEPON', 'Elektronik'],
    ['MONITOR', 'Elektronik'],
    ['KEYBOARD', 'Elektronik'],
    ['SPEAKER', 'Elektronik'],
    ['HEADSET', 'Elektronik'],
    ['CHARGER', 'Elektronik'],
    ['REMOTE', 'Elektronik'],
    ['PRINTER', 'Elektronik'],
    ['KOMPOR', 'Elektronik'],
    ['BLENDER', 'Elektronik'],
    ['SETRIKA', 'Elektronik'],

    // ===== TEMPAT =====
    ['SEKOLAH', 'Tempat'],
    ['RUMAH SAKIT', 'Tempat'],
    ['PERKANTORAN', 'Tempat'],
    ['BANDARA', 'Tempat'],
    ['STASIUN', 'Tempat'],
    ['TERMINAL', 'Tempat'],
    ['PERPUSTAKAAN', 'Tempat'],
    ['UNIVERSITAS', 'Pendidikan'],
    ['MUSEUM', 'Tempat'],
    ['STADION', 'Tempat'],
    ['RESTORAN', 'Tempat'],
    ['SUPERMARKET', 'Tempat'],
    ['MAL', 'Tempat'],
    ['POM BENSIN', 'Tempat'],

    // ===== ALAM =====
    ['GUNUNG', 'Alam'],
    ['SUNGAI', 'Alam'],
    ['PANTAI', 'Alam'],
    ['AIR TERJUN', 'Alam'],
    ['PEMANDANGAN', 'Alam'],
    ['PELABUHAN', 'Tempat'],
    ['PERKEBUNAN', 'Alam'],
    ['PERSAWAHAN', 'Alam'],
    ['PEGUNUNGAN', 'Alam'],
    ['SAMUDRA', 'Alam'],

    // ===== PROFESI =====
    ['DOKTER', 'Profesi'],
    ['PERAWAT', 'Profesi'],
    ['GURU', 'Profesi'],
    ['POLISI', 'Profesi'],
    ['TENTARA', 'Profesi'],
    ['PILOT', 'Profesi'],
    ['NELAYAN', 'Profesi'],
    ['PETANI', 'Profesi'],
    ['PEDAGANG', 'Profesi'],
    ['ARSITEK', 'Profesi'],
    ['PROGRAMMER', 'Profesi'],
    ['MEKANIK', 'Profesi'],
    ['JURNALIS', 'Profesi'],
    ['PENYANYI', 'Profesi'],
    ['AKTOR', 'Profesi'],

    // ===== KOTA =====
    ['JAKARTA', 'Kota'],
    ['BANDUNG', 'Kota'],
    ['SURABAYA', 'Kota'],
    ['SEMARANG', 'Kota'],
    ['DEPOK', 'Kota'],
    ['BEKASI', 'Kota'],
    ['BOGOR', 'Kota'],
    ['MALANG', 'Kota'],
    ['MEDAN', 'Kota'],
    ['PADANG', 'Kota'],
    ['MANADO', 'Kota'],
    ['DENPASAR', 'Kota'],
    ['BATAM', 'Kota'],
    ['BALIKPAPAN', 'Kota'],

    // ===== LAINNYA =====
    ['KEMERAHAN', 'Kondisi'],
    ['KEBAHAGIAAN', 'Perasaan'],
    ['KESUKSESAN', 'Kondisi'],
    ['PERMAINAN', 'Aktivitas'],
    ['OLAHRAGA', 'Aktivitas'],
    ['PETUALANGAN', 'Aktivitas'],
    ['PERJALANAN', 'Aktivitas'],
    ['PERAYAAN', 'Kegiatan'],
    ['PERNIKAHAN', 'Acara'],
    ['ULANG TAHUN', 'Acara'],
  ],

  sulit: [
    // ===== INDONESIA =====
    ['INDONESIA', 'Negara'],
    ['KEMERDEKAAN', 'Sejarah'],
    ['PROKLAMASI', 'Sejarah'],
    ['PANCASILA', 'Ideologi'],
    ['NUSANTARA', 'Wilayah'],
    ['BHINNEKA', 'Semboyan'],
    ['GARUDA', 'Simbol negara'],
    ['KEBUDAYAAN', 'Budaya'],
    ['MASYARAKAT', 'Sosial'],
    ['PEMBANGUNAN', 'Kegiatan'],

    // ===== KOTA =====
    ['YOGYAKARTA', 'Kota'],
    ['PALEMBANG', 'Kota'],
    ['MAKASSAR', 'Kota'],
    ['BALIKPAPAN', 'Kota'],
    ['BANJARMASIN', 'Kota'],
    ['PEKANBARU', 'Kota'],
    ['BANDARLAMPUNG', 'Kota'],
    ['PONTIANAK', 'Kota'],
    ['SAMARINDA', 'Kota'],
    ['JAYAPURA', 'Kota'],

    // ===== PULAU =====
    ['KALIMANTAN', 'Pulau'],
    ['SUMATERA', 'Pulau'],
    ['SULAWESI', 'Pulau'],
    ['PAPUA', 'Pulau'],
    ['BALI', 'Pulau'],
    ['LOMBOK', 'Pulau'],
    ['FLORES', 'Pulau'],
    ['SUMBAWA', 'Pulau'],
    ['MADURA', 'Pulau'],

    // ===== HEWAN =====
    ['ORANGUTAN', 'Hewan'],
    ['KANGGURU', 'Hewan'],
    ['KOMODO', 'Hewan'],
    ['BADAK', 'Hewan'],
    ['BANTENG', 'Hewan'],
    ['BERUANG', 'Hewan'],
    ['SIMPA NSE', 'Hewan'],
    ['KAKTUS', 'Tanaman'],
    ['BUAYA MUARA', 'Hewan'],
    ['KUPU-KUPU', 'Hewan'],

    // ===== TEKNOLOGI =====
    ['KOMPUTER', 'Elektronik'],
    ['TELEVISI', 'Elektronik'],
    ['SMARTPHONE', 'Teknologi'],
    ['KOMUNIKASI', 'Teknologi'],
    ['INTERNET', 'Teknologi'],
    ['PERANGKAT', 'Teknologi'],
    ['PERANGKAT LUNAK', 'Teknologi'],
    ['PROGRAMMING', 'Teknologi'],
    ['DATABASE', 'Teknologi'],
    ['SERVER', 'Teknologi'],
    ['JARINGAN', 'Teknologi'],
    ['KEYBOARD', 'Elektronik'],
    ['MIKROFON', 'Elektronik'],
    ['PROYEKTOR', 'Elektronik'],
    ['KOMPONEN', 'Teknologi'],

    // ===== MAKANAN =====
    ['MARTABAK', 'Makanan'],
    ['PEMPEK', 'Makanan'],
    ['RENDANG', 'Makanan'],
    ['KETUPAT', 'Makanan'],
    ['KLEPON', 'Makanan'],
    ['SERABI', 'Makanan'],
    ['BROWNIES', 'Makanan'],
    ['PUDING', 'Makanan'],
    ['SPAGETI', 'Makanan'],
    ['LASAGNA', 'Makanan'],
    ['SANDWICH', 'Makanan'],
    ['CROISSANT', 'Makanan'],
    ['PANCAKE', 'Makanan'],
    ['DONAT', 'Makanan'],

    // ===== PROFESI =====
    ['PENGACARA', 'Profesi'],
    ['WARTAWAN', 'Profesi'],
    ['INSINYUR', 'Profesi'],
    ['ILMUWAN', 'Profesi'],
    ['ASTRONOT', 'Profesi'],
    ['PRESENTER', 'Profesi'],
    ['FOTOGRAFER', 'Profesi'],
    ['DESAINER', 'Profesi'],
    ['PROGRAMMER', 'Profesi'],
    ['DEVELOPER', 'Profesi'],
    ['MANAJER', 'Profesi'],
    ['DIREKTUR', 'Profesi'],

    // ===== TEMPAT =====
    ['PERPUSTAKAAN', 'Tempat'],
    ['UNIVERSITAS', 'Pendidikan'],
    ['LABORATORIUM', 'Tempat'],
    ['OBSERVATORIUM', 'Tempat'],
    ['PENGADILAN', 'Tempat'],
    ['KEDUTAAN', 'Tempat'],
    ['PUSKESMAS', 'Tempat'],
    ['PELABUHAN', 'Tempat'],
    ['BANDARA', 'Tempat'],
    ['PERKANTORAN', 'Tempat'],

    // ===== ABSTRAK =====
    ['KECERDASAN', 'Kemampuan'],
    ['PENGETAHUAN', 'Kemampuan'],
    ['PENGALAMAN', 'Kondisi'],
    ['KEBERANIAN', 'Sifat'],
    ['KEJUJURAN', 'Sifat'],
    ['PERSAHABATAN', 'Hubungan'],
    ['KEBAHAGIAAN', 'Perasaan'],
    ['KESEDIHAN', 'Perasaan'],
    ['KEGEMBIRAAN', 'Perasaan'],
    ['KEBERHASILAN', 'Kondisi'],
    ['KEGAGALAN', 'Kondisi'],
    ['PERJUANGAN', 'Aktivitas'],
    ['PETUALANGAN', 'Aktivitas'],
    ['PERKEMBANGAN', 'Proses'],
    ['PERUBAHAN', 'Proses'],
  ],
};

// Opsional: data/words.json = { "mudah": [["KUCING","Hewan"], ...], "sedang": [...], "sulit": [...] }
async function loadWords(level) {
  let list = BANK[level] || BANK[DEFAULT_LEVEL];
  try {
    const file = path.join(__dirname, '..', 'data', 'words.json');
    if (fs.existsSync(file)) {
      const custom = JSON.parse(fs.readFileSync(file, 'utf8'))[level];
      if (Array.isArray(custom) && custom.length) list = custom;
    }
  } catch (e) { console.error('[words] words.json gagal dibaca:', e.message); }
  return list
    .map(([w, c]) => [String(w).toUpperCase().replace(/[^A-Z]/g, ''), String(c || 'Umum')])
    .filter(([w]) => w.length >= 3);
}

module.exports = { loadWords, LEVELS, DEFAULT_LEVEL };
